const swaggerJsdoc = require('swagger-jsdoc');

// Complete paths generated by introspecting the live router (npm run openapi).
// Regenerate whenever routes change so the docs never drift from reality.
let generated = { paths: {} };
try { generated = require('./openapi.generated.json'); } catch (_) { /* run `npm run openapi` */ }

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Rudraganga — Astrology & Wellness Platform API',
      version: '1.0.0',
      description:
        'Backend API for the Flutter apps (end-user + astrologer) and the admin panel.\n\n' +
        '**Envelope:** every response is `{ "success": true, "data": ... }` on success, ' +
        'or `{ "success": false, "message": "...", "errors": [...] }` on failure.\n\n' +
        '**Auth:** send `Authorization: Bearer <accessToken>`. Tokens come from ' +
        '`POST /api/auth/verify-otp`; refresh with `POST /api/auth/refresh` (refreshToken in body — no cookies). ' +
        'Realtime is Socket.io with the same JWT in `handshake.auth.token`.',
    },
    servers: [
      { url: '/', description: 'Current host' },
      { url: 'http://10.0.2.2:5050', description: 'Android emulator → host machine' },
      { url: 'http://localhost:5050', description: 'iOS simulator / local' },
    ],
    components: {
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      },
    },
    security: [{ bearerAuth: [] }],
    // Generated paths are the source of truth; JSDoc annotations (below) refine
    // individual operations on top of these.
    paths: generated.paths || {},
  },
  apis: ['./routes/*.js'],
};

module.exports = swaggerJsdoc(options);
