const mongoose = require('mongoose');

/**
 * A poll shown to the audience during a live broadcast. Auto-generated by the AI
 * (aiService/OpenAI) from the broadcast topic; audience members vote once. The
 * running tally is broadcast over sockets and persisted here.
 *
 *   options   [{ text, votes }] — votes is a denormalized counter for fast reads
 *   voters    user ids that have voted (one vote per user; guards double-voting)
 *   active    true while accepting votes; the astrologer/end closes it
 */
const optionSchema = new mongoose.Schema(
  {
    text: { type: String, required: true, trim: true, maxlength: 80 },
    votes: { type: Number, default: 0 },
  },
  { _id: true }
);

const livePollSchema = new mongoose.Schema(
  {
    liveSession: { type: mongoose.Schema.Types.ObjectId, ref: 'LiveSession', required: true, index: true },
    question: { type: String, required: true, trim: true, maxlength: 140 },
    options: { type: [optionSchema], validate: (v) => v.length >= 2 && v.length <= 4 },
    voters: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    active: { type: Boolean, default: true, index: true },
    source: { type: String, enum: ['ai', 'manual'], default: 'ai' },
  },
  { timestamps: true }
);

module.exports = mongoose.model('LivePoll', livePollSchema);
